### ISSUE TITLE
nightly 1.x issues

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#27]
https://jenkins.scala-sbt.org:8592/job/sbt-community/339/consoleFull

### self building sbt using sbt 1.x

```
[22:51:53] [sbt:error] /localhome/jenkinssbt/workspace/sbt-community/target-0.9.12/extraction/097f7d4ca68974a51a1e6d918f8778364fd2f3cc/projects/2b41117630af4403c7aa80ad90bd4191901b34d3/build.sbt:0: warning: imported `ScriptedPlugin' is permanently hidden by definition of object ScriptedPlugin
[22:51:53] [sbt:error] import _root_.sbt.plugins.IvyPlugin, _root_.sbt.plugins.JvmPlugin, _root_.sbt.plugins.CorePlugin, _root_.sbt.ScriptedPlugin, _root_.sbt.plugins.SbtPlugin, _root_.sbt.plugins.JUnitXmlReportPlugin, _root_.sbt.plugins.Giter8TemplatePlugin, _root_.com.typesafe.dbuild.plugin.DBuildPlugin, _root_.com.typesafe.tools.mima.plugin.MimaPlugin, _root_.sbthouserules.BetterGitVersionPlugin, _root_.sbthouserules.BintraySettingPlugin, _root_.sbthouserules.HouseRulesPlugin, _root_.sbthouserules.StylePlugin, _root_.com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin, _root_.com.lucidchart.sbt.scalafmt.ScalafmtPlugin, _root_.com.lucidchart.sbt.scalafmt.ScalafmtSbtPlugin, _root_.com.typesafe.sbt.GitBranchPrompt, _root_.com.typesafe.sbt.GitPlugin, _root_.com.typesafe.sbt.GitVersioning, _root_.bintray.BintrayPlugin, _root_.com.typesafe.sbt.SbtPgp, _root_.sbt.contraband.ContrabandPlugin, _root_.sbt.contraband.JsonCodecPlugin, _root_.de.heikoseeberger.sbtheader.AutomateHeaderPlugin, _root_.de.heikoseeberger.sbtheader.HeaderPlugin, _root_.sbtbuildinfo.BuildInfoPlugin, _root_.sbtwhitesource.WhiteSourcePlugin
[22:51:53] [sbt:error]                                                                                                              ^
[22:51:53] [sbt:error] /localhome/jenkinssbt/workspace/sbt-community/target-0.9.12/extraction/097f7d4ca68974a51a1e6d918f8778364fd2f3cc/projects/2b41117630af4403c7aa80ad90bd4191901b34d3/build.sbt:702: error: reference to scripted is ambiguous;
[22:51:53] [sbt:error] it is imported twice in the same scope by
[22:51:53] [sbt:error] import ScriptedPlugin.autoImport._
[22:51:53] [sbt:error] and import _root_.sbt.ScriptedPlugin.autoImport._
[22:51:53] [sbt:error]     scripted := scriptedTask.evaluated,
[22:51:53] [sbt:error]     ^
```

### zinc

```
[22:55:48] [sbt-zinc:error] /localhome/jenkinssbt/workspace/sbt-community/target-0.9.12/extraction/097f7d4ca68974a51a1e6d918f8778364fd2f3cc/projects/77a716f0a9423884614184da7759ebcd224ee21f/build.sbt:627: error: reference to scriptedBufferLog is ambiguous;
[22:55:48] [sbt-zinc:error] it is imported twice in the same scope by
[22:55:48] [sbt-zinc:error] import Scripted._
[22:55:48] [sbt-zinc:error] and import _root_.sbt.ScriptedPlugin.autoImport._
[22:55:48] [sbt-zinc:error]     scriptedBufferLog.value,
[22:55:48] [sbt-zinc:error]     ^
[22:55:48] [sbt-zinc:error] /localhome/jenkinssbt/workspace/sbt-community/target-0.9.12/extraction/097f7d4ca68974a51a1e6d918f8778364fd2f3cc/projects/77a716f0a9423884614184da7759ebcd224ee21f/build.sbt:659: error: reference to scriptedBufferLog is ambiguous;
[22:55:48] [sbt-zinc:error] it is imported twice in the same scope by
[22:55:48] [sbt-zinc:error] import Scripted._
[22:55:48] [sbt-zinc:error] and import _root_.sbt.ScriptedPlugin.autoImport._
[22:55:48] [sbt-zinc:error]     scriptedBufferLog.value,
[22:55:48] [sbt-zinc:error]     ^
[22:55:48] [sbt-zinc] [error] sbt.compiler.EvalException: Type error in expression
[22:55:48] [sbt-zinc] [error] sbt.compiler.EvalException: Type error in expression
[22:55:48] [sbt-zinc] [error] Use 'last' for the full log.
[22:55:48] [sbt-zinc] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[22:55:48] [sbt-zinc:error] java.lang.RuntimeException: 
[22:55:48] [sbt-zinc:error] 	at scala.sys.package$.error(package.scala:27)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:94)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:75)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:66)
[22:56:05] [sbt-zinc:error] 	at sbt.IO$.withTemporaryFile(IO.scala:389)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:66)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:107)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:85)
[22:56:05] [sbt-zinc:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:22)
```

### circe

```
[22:46:34] [circe] [error] java.lang.RuntimeException: These subprojects were not found: "parser", "tests", "scodec", "testing", "numbers", "generic", "literal", "core".  Found: "shapesJS", "numbersTestingJVM", "testingJVM", "genericJVM", "genericExtrasJS", "literalJVM", "parserJVM", "literalJS", "parserJS", "scalajs", "docs", "shapesJVM", "java8JS", "coreJS", "hygieneJVM", "genericExtrasJVM", "testingJS", "opticsJVM", "genericJS", "hygieneJS", "coreJVM", "testsJS", "numbersTestingJS", "opticsJS", "refinedJS", "circe", "scodecJVM", "scodecJS", "refinedJVM", "java8JVM", "numbersJS", "testsJVM", "jawn", "numbersJVM", "benchmark". 
[22:46:34] [circe] [error] 	at scala.sys.package$.error(package.scala:27)
[22:46:34] [circe] [error] 	at com.typesafe.dbuild.plugin.DBuildRunner$.verifySubProjects(DBuildRunner.scala:79)
[22:46:34] [circe] [error] 	at com.typesafe.dbuild.plugin.DBuildRunner$.getSortedProjects(DBuildRunner.scala:84)
[22:46:34] [circe] [error] 	at com.typesafe.dbuild.plugin.DependencyAnalysis$.printDependencies(DependencyAnalysis.scala:121)
[22:46:34] [circe] [error] 	at com.typesafe.dbuild.plugin.DependencyAnalysis$.$anonfun$printCmd$2(DependencyAnalysis.scala:299)
[22:46:34] [circe] [error] 	at com.typesafe.dbuild.plugin.StateHelpers$.saveLastMsg(StateHelpers.scala:40)
```

**Comment by cunei** [comment]
Circe is now fixed
