### ISSUE TITLE
reference to test is ambiguous

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#28]
```
[22:48:52] [coursier] [error] /localhome/jenkinssbt/workspace/sbt-community/target-0.9.12/extraction/097f7d4ca68974a51a1e6d918f8778364fd2f3cc/projects/3582724d1f9eeb5205ffbdefd488bf11a6603c8d/project/Settings.scala:119:5: reference to test is ambiguous;
[22:48:52] [coursier] [error] it is imported twice in the same scope by
[22:48:52] [coursier] [error] import sbt.Keys._
[22:48:52] [coursier] [error] and import sbt._
[22:48:52] [coursier] [error]     test.in(Test) := {},
[22:48:52] [coursier] [error]     ^
[22:48:52] [coursier] [error] one error found
[22:48:52] [coursier] [error] (Compile / compileIncremental) Compilation failed
[22:48:52] [coursier] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[22:48:52] [coursier:error] java.lang.RuntimeException: 
[22:48:52] [coursier:error] 	at scala.sys.package$.error(package.scala:27)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:94)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:75)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:66)
[22:48:52] [coursier:error] 	at sbt.IO$.withTemporaryFile(IO.scala:389)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:66)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:107)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:85)
[22:48:52] [coursier:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:22)
```

**Comment by cunei** [comment]
Done, closing.
