### ISSUE TITLE
swoval fails in sbt community build

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#40]
```
[23:21:29] [swoval] [error] java.io.IOException: Cannot run program "clang-format": error=2, No such file or directory
[23:21:29] [swoval] [error] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[23:21:29] [swoval] [error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[23:21:29] [swoval] [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:119)
[23:21:29] [swoval] [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:135)
[23:21:29] [swoval] [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:108)
[23:21:29] [swoval] [error] 	at com.swoval.format.impl.ClangFormatter$.apply(ClangFormatter.scala:23)
[23:21:29] [swoval] [error] 	at com.swoval.format.impl.ClangFormatter$.apply(ClangFormatter.scala:13)
[23:21:29] [swoval] [error] 	at com.swoval.format.Formatter$$anonfun$$nestedInanonfun$apply$3$1.applyOrElse(Formatter.scala:21)
[23:21:29] [swoval] [error] 	at com.swoval.format.Formatter$$anonfun$$nestedInanonfun$apply$3$1.applyOrElse(Formatter.scala:20)
[23:21:29] [swoval] [error] 	at scala.PartialFunction.$anonfun$runWith$1$adapted(PartialFunction.scala:145)
[23:21:29] [swoval] [error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[23:21:29] [swoval] [error] 	at scala.collection.TraversableLike.collect(TraversableLike.scala:274)
[23:21:29] [swoval] [error] 	at scala.collection.TraversableLike.collect$(TraversableLike.scala:272)
[23:21:29] [swoval] [error] 	at scala.collection.immutable.List.collect(List.scala:327)
[23:21:29] [swoval] [error] 	at com.swoval.format.Formatter$.$anonfun$apply$3(Formatter.scala:20)
[23:21:29] [swoval] [error] 	at com.swoval.format.Formatter$.$anonfun$apply$3$adapted(Formatter.scala:13)
[23:21:29] [swoval] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[23:21:29] [swoval] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[23:21:29] [swoval] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[23:21:29] [swoval] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[23:21:29] [swoval] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[23:21:29] [swoval] [error] 	at sbt.Execute.work(Execute.scala:277)
[23:21:29] [swoval] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[23:21:29] [swoval] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[23:21:29] [swoval] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[23:21:29] [swoval] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:21:29] [swoval] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:21:29] [swoval] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:21:29] [swoval] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:21:29] [swoval] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:21:29] [swoval] [error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eed3si9n** [comment]
Toni said he installed clang-format, and I've confirmed that the build succeeded yesterday.
