### ISSUE TITLE
twitter-util fails in sbt community build

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#43]
```
[05:06:36] [twitter-util:error] Mar 31, 2019 5:06:36 AM com.twitter.app.LoadService$ $anonfun$loadImpls$7
[05:06:36] [twitter-util:error] SEVERE: LoadService: failed to instantiate 'com.twitter.app.LoadServiceFailingClass' for the requested service 'com.twitter.app.LoadServiceMaybeInterface'
[05:06:36] [twitter-util:error] java.lang.RuntimeException: Cannot instanciate this!
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadServiceFailingClass.<init>(LoadServiceTest.scala:26)
[05:06:36] [twitter-util:error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:06:36] [twitter-util:error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:06:36] [twitter-util:error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:06:36] [twitter-util:error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:06:36] [twitter-util:error] 	at java.lang.Class.newInstance(Class.java:442)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.$anonfun$loadImpls$7(LoadService.scala:195)
[05:06:36] [twitter-util:error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[05:06:36] [twitter-util:error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
[05:06:36] [twitter-util:error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
[05:06:36] [twitter-util:error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[05:06:36] [twitter-util:error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[05:06:36] [twitter-util:error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[05:06:36] [twitter-util:error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.loadImpls(LoadService.scala:184)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.apply(LoadService.scala:138)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.apply(LoadService.scala:152)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadServiceTest.$anonfun$new$5(LoadServiceTest.scala:81)
[05:06:36] [twitter-util:error] 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[05:06:36] [twitter-util:error] 	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[05:06:36] [twitter-util:error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[05:06:36] [twitter-util:error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[05:06:36] [twitter-util:error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[05:06:36] [twitter-util:error] 	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[05:06:36] [twitter-util:error] 	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[05:06:36] [twitter-util:error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.Suite.run(Suite.scala:1147)
[05:06:36] [twitter-util:error] 	at org.scalatest.Suite.run$(Suite.scala:1129)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[05:06:36] [twitter-util:error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:499)
[05:06:36] [twitter-util:error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:126)
[05:06:36] [twitter-util:error] 	at sbt.TestRunner.run(TestFramework.scala:137)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:296)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:259)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:296)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:296)
[05:06:36] [twitter-util:error] 	at sbt.TestFunction.apply(TestFramework.scala:308)
[05:06:36] [twitter-util:error] 	at sbt.Tests$.processRunnable$1(Tests.scala:347)
[05:06:36] [twitter-util:error] 	at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
[05:06:36] [twitter-util:error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[05:06:36] [twitter-util:error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[05:06:36] [twitter-util:error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[05:06:36] [twitter-util:error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[05:06:36] [twitter-util:error] 	at sbt.Execute.work(Execute.scala:277)
[05:06:36] [twitter-util:error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[05:06:36] [twitter-util:error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[05:06:36] [twitter-util:error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[05:06:36] [twitter-util:error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:06:36] [twitter-util:error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[05:06:36] [twitter-util:error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:06:36] [twitter-util:error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[05:06:36] [twitter-util:error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[05:06:36] [twitter-util:error] 	at java.lang.Thread.run(Thread.java:748)
[05:06:36] [twitter-util:error] 
[05:06:36] [twitter-util:error] Mar 31, 2019 5:06:36 AM com.twitter.app.LoadService$ $anonfun$loadImpls$7
[05:06:36] [twitter-util:error] SEVERE: LoadService: failed to instantiate 'com.twitter.app.LoadServiceFailingClass' for the requested service 'com.twitter.app.LoadServiceMaybeInterface'
[05:06:36] [twitter-util:error] java.lang.RuntimeException: Cannot instanciate this!
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadServiceFailingClass.<init>(LoadServiceTest.scala:26)
[05:06:36] [twitter-util:error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:06:36] [twitter-util:error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:06:36] [twitter-util:error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:06:36] [twitter-util:error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:06:36] [twitter-util:error] 	at java.lang.Class.newInstance(Class.java:442)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.$anonfun$loadImpls$7(LoadService.scala:195)
[05:06:36] [twitter-util:error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[05:06:36] [twitter-util:error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
[05:06:36] [twitter-util:error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
[05:06:36] [twitter-util:error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[05:06:36] [twitter-util:error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[05:06:36] [twitter-util:error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[05:06:36] [twitter-util:error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.loadImpls(LoadService.scala:184)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.apply(LoadService.scala:138)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadService$.apply(LoadService.scala:152)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadServiceTest.$anonfun$new$7(LoadServiceTest.scala:88)
[05:06:36] [twitter-util:error] 	at com.twitter.util.Local.let(Local.scala:4997)
[05:06:36] [twitter-util:error] 	at com.twitter.util.registry.GlobalRegistry$.withRegistry(Registry.scala:127)
[05:06:36] [twitter-util:error] 	at com.twitter.app.LoadServiceTest.$anonfun$new$6(LoadServiceTest.scala:87)
[05:06:36] [twitter-util:error] 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[05:06:36] [twitter-util:error] 	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[05:06:36] [twitter-util:error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[05:06:36] [twitter-util:error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[05:06:36] [twitter-util:error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[05:06:36] [twitter-util:error] 	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[05:06:36] [twitter-util:error] 	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[05:06:36] [twitter-util:error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.Suite.run(Suite.scala:1147)
[05:06:36] [twitter-util:error] 	at org.scalatest.Suite.run$(Suite.scala:1129)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
[05:06:36] [twitter-util:error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
[05:06:36] [twitter-util:error] 	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
[05:06:36] [twitter-util:error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[05:06:36] [twitter-util:error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:499)
[05:06:36] [twitter-util:error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:126)
[05:06:36] [twitter-util:error] 	at sbt.TestRunner.run(TestFramework.scala:137)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:296)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:259)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:296)
[05:06:36] [twitter-util:error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:296)
[05:06:36] [twitter-util:error] 	at sbt.TestFunction.apply(TestFramework.scala:308)
[05:06:36] [twitter-util:error] 	at sbt.Tests$.processRunnable$1(Tests.scala:347)
[05:06:36] [twitter-util:error] 	at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
[05:06:36] [twitter-util:error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[05:06:36] [twitter-util:error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[05:06:36] [twitter-util:error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[05:06:36] [twitter-util:error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[05:06:38] [twitter-util:error] 	at sbt.Execute.work(Execute.scala:277)
[05:06:38] [twitter-util:error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[05:06:38] [twitter-util:error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[05:06:38] [twitter-util:error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[05:06:38] [twitter-util:error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:06:38] [twitter-util:error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[05:06:38] [twitter-util:error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:06:38] [twitter-util:error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[05:06:38] [twitter-util:error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[05:06:38] [twitter-util:error] 	at java.lang.Thread.run(Thread.java:748)
[05:06:38] [twitter-util:error] 
[05:06:38] [twitter-util:error] Mar 31, 2019 5:06:37 AM com.twitter.app.LoadService$ $anonfun$loadImpls$6
[05:06:38] [twitter-util:error] INFO: LoadService: skipped com.twitter.app.LoadServiceMultipleImpls1 due to deny list flag
[05:06:38] [twitter-util:error] Mar 31, 2019 5:06:37 AM com.twitter.app.LoadService$ $anonfun$loadImpls$6
[05:06:38] [twitter-util:error] INFO: LoadService: skipped com.twitter.app.LoadServiceMultipleImpls2 due to deny list flag
[05:06:38] [twitter-util:error] Mar 31, 2019 5:06:37 AM com.twitter.app.LoadService$ $anonfun$bind$1
[05:06:38] [twitter-util:error] WARNING: Replaced existing `LoadService.bind` for `com.twitter.app.LoadServiceTest$BindMultiple$1`, old='List(com.twitter.app.LoadServiceTest$$anon$3@356ec5ab)', new='List(com.twitter.app.LoadServiceTest$$anon$4@472a37c0)'
```

**Comment by eed3si9n** [comment]
https://jenkins.scala-sbt.org:8592/job/sbt-community/650/console

```
[03:40:01] [info] Project twitter-util----------------: SUCCESS (project rebuilt ok)
```
