### ISSUE TITLE
sbt.Task cannot be cast to scala.Option

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#9]
https://jenkins.scala-sbt.org:8592/job/sbt%20validator/41/console

```
[sbt212-io:error] java.lang.ClassCastException: sbt.Task cannot be cast to scala.Option
[sbt212-io:error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[sbt212-io:error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:176)
[sbt212-io:error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:135)
[sbt212-io:error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:69)
[sbt212-io:error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:78)
[sbt212-io:error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:74)
[sbt212-io:error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[sbt212-io:error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[sbt212-io:error] 	at java.lang.Thread.run(Thread.java:745)
[sbt212-io] [error] java.lang.ClassCastException: sbt.Task cannot be cast to scala.Option
[sbt212-io] [error] Use 'last' for the full log.
[sbt212-io] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[sbt212-io:error] java.lang.RuntimeException: sbt.Task cannot be cast to scala.Option
[sbt212-io:error] 	at scala.sys.package$.error(package.scala:27)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:92)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:73)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:73)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:73)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[sbt212-io:error] 	at sbt.IO$.withTemporaryFile(IO.scala:389)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtBuilder$.buildSbtProject(SbtBuildRunner.scala:87)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:93)
[sbt212-io:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:21)
[sbt212-io] --== End Building sbt212-io ==--
```

I'm not sure what's going on here.

**Comment by cunei** [comment]
This has been solved as part of the sbt 1.0.0 support; closing.
